<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<!-- wp:group {"anchor":"gallery","align":"full","className":"pbs-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|80","bottom":"var:preset|spacing|80"}}},"layout":{"type":"constrained"}} -->
<div id="gallery" class="wp-block-group alignfull pbs-section" style="padding-top:var(--wp--preset--spacing--80);padding-bottom:var(--wp--preset--spacing--80)">
  <!-- wp:group {"align":"wide","className":"pbs-section-heading"} --><div class="wp-block-group alignwide pbs-section-heading"><!-- wp:paragraph {"className":"pbs-kicker"} --><p class="pbs-kicker">نمونه‌کارها</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"heading-2"} --><h2 class="wp-block-heading has-heading-2-font-size">قبل و بعد، با اجازه انتشار</h2><!-- /wp:heading --><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color">تصاویر زیر جای‌نگهدار هستند. آن‌ها را فقط با عکس‌های مجاز جایگزین کنید.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
  <!-- wp:group {"align":"wide"} --><div class="wp-block-group alignwide"><!-- wp:shortcode -->[barbershop_before_after_gallery limit="6"]<!-- /wp:shortcode --></div><!-- /wp:group -->
  <!-- wp:columns {"align":"wide","className":"pbs-gallery-grid"} -->
  <div class="wp-block-columns alignwide pbs-gallery-grid">
    <!-- wp:column --><div class="wp-block-column"><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"pbs-gallery-item"} --><figure class="wp-block-image size-full pbs-gallery-item"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-1.svg' ) ); ?>" alt="جای‌نگهدار نمونه‌کار شماره یک" width="1200" height="900"/><figcaption class="wp-element-caption">[عنوان نمونه‌کار اول]</figcaption></figure><!-- /wp:image --></div><!-- /wp:column -->
    <!-- wp:column --><div class="wp-block-column"><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"pbs-gallery-item"} --><figure class="wp-block-image size-full pbs-gallery-item"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-2.svg' ) ); ?>" alt="جای‌نگهدار نمونه‌کار شماره دو" width="1200" height="900"/><figcaption class="wp-element-caption">[عنوان نمونه‌کار دوم]</figcaption></figure><!-- /wp:image --></div><!-- /wp:column -->
    <!-- wp:column --><div class="wp-block-column"><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"pbs-gallery-item"} --><figure class="wp-block-image size-full pbs-gallery-item"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-3.svg' ) ); ?>" alt="جای‌نگهدار نمونه‌کار شماره سه" width="1200" height="900"/><figcaption class="wp-element-caption">[عنوان نمونه‌کار سوم]</figcaption></figure><!-- /wp:image --></div><!-- /wp:column -->
  </div><!-- /wp:columns -->
</div><!-- /wp:group -->
