<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<!-- wp:group {"anchor":"reviews","align":"full","className":"pbs-section","backgroundColor":"navy","style":{"spacing":{"padding":{"top":"var:preset|spacing|80","bottom":"var:preset|spacing|80"}}},"layout":{"type":"constrained"}} -->
<div id="reviews" class="wp-block-group alignfull pbs-section has-navy-background-color has-background" style="padding-top:var(--wp--preset--spacing--80);padding-bottom:var(--wp--preset--spacing--80)">
  <!-- wp:group {"align":"wide","className":"pbs-section-heading"} --><div class="wp-block-group alignwide pbs-section-heading"><!-- wp:paragraph {"className":"pbs-kicker"} --><p class="pbs-kicker">نظر مشتریان</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"heading-2"} --><h2 class="wp-block-heading has-heading-2-font-size">اعتماد، از تجربه واقعی می‌آید</h2><!-- /wp:heading --><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color">فقط نظرهای واقعی و تأییدشده را با اجازه انتشار وارد کنید.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
  <!-- wp:columns {"align":"wide","className":"pbs-card-grid"} -->
  <div class="wp-block-columns alignwide pbs-card-grid">
    <!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"pbs-card pbs-review-card"} --><div class="wp-block-group pbs-card pbs-review-card"><!-- wp:quote --><blockquote class="wp-block-quote"><p>[نظر مشتری اول]</p><cite>[نام مشتری اول]</cite></blockquote><!-- /wp:quote --></div><!-- /wp:group --></div><!-- /wp:column -->
    <!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"pbs-card pbs-review-card"} --><div class="wp-block-group pbs-card pbs-review-card"><!-- wp:quote --><blockquote class="wp-block-quote"><p>[نظر مشتری دوم]</p><cite>[نام مشتری دوم]</cite></blockquote><!-- /wp:quote --></div><!-- /wp:group --></div><!-- /wp:column -->
    <!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"pbs-card pbs-review-card"} --><div class="wp-block-group pbs-card pbs-review-card"><!-- wp:quote --><blockquote class="wp-block-quote"><p>[نظر مشتری سوم]</p><cite>[نام مشتری سوم]</cite></blockquote><!-- /wp:quote --></div><!-- /wp:group --></div><!-- /wp:column -->
  </div><!-- /wp:columns -->
</div><!-- /wp:group -->
