<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<!-- wp:group {"anchor":"services","align":"full","className":"pbs-section","backgroundColor":"graphite","style":{"spacing":{"padding":{"top":"var:preset|spacing|80","bottom":"var:preset|spacing|80"}}},"layout":{"type":"constrained"}} -->
<div id="services" class="wp-block-group alignfull pbs-section has-graphite-background-color has-background" style="padding-top:var(--wp--preset--spacing--80);padding-bottom:var(--wp--preset--spacing--80)">
  <!-- wp:group {"align":"wide","className":"pbs-section-heading","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group alignwide pbs-section-heading"><div class="wp-block-group"><p class="pbs-kicker has-muted-gold-color has-text-color">خدمات</p><h2 class="wp-block-heading has-heading-2-font-size">جزئیات کوچک، تفاوت بزرگ</h2></div><p class="has-sand-color has-text-color">مدت، قیمت و توضیحات دقیق هر خدمت را پیش از انتشار جایگزین کنید.</p></div><!-- /wp:group -->
  <!-- wp:columns {"align":"wide","className":"pbs-card-grid"} --><div class="wp-block-columns alignwide pbs-card-grid">
    <!-- wp:column --><div class="wp-block-column"><div class="wp-block-group pbs-card"><span class="pbs-number">01</span><h3 class="wp-block-heading has-heading-3-font-size">اصلاح و فرم‌دهی مو</h3><p>[توضیح خدمت، مدت تقریبی و محدوده قیمت]</p></div></div><!-- /wp:column -->
    <!-- wp:column --><div class="wp-block-column"><div class="wp-block-group pbs-card"><span class="pbs-number">02</span><h3 class="wp-block-heading has-heading-3-font-size">اصلاح و طراحی ریش</h3><p>[توضیح خدمت، مدت تقریبی و محدوده قیمت]</p></div></div><!-- /wp:column -->
    <!-- wp:column --><div class="wp-block-column"><div class="wp-block-group pbs-card"><span class="pbs-number">03</span><h3 class="wp-block-heading has-heading-3-font-size">مشاوره استایل</h3><p>[توضیح خدمت، مدت تقریبی و محدوده قیمت]</p></div></div><!-- /wp:column -->
  </div><!-- /wp:columns -->
</div><!-- /wp:group -->
